---
title: "simple document"
output: github_document
date: "2023-09-19"
---

Let's import the `FAS_litters.csv` csv using a relative path.

```{r}
library(tidyverse)
```

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df) ##to clean up the names of the columns---convert spaces and uppercases to all lower cases and underscores(typical r name writing)


```

Import the same data set using an absolute path.

```{r}
litters_df_abs= 
  read_csv("~/Desktop/data_wrangling_i/data/FAS_litters.csv")

litters_df_abs = 
  janitor::clean_names(litters_df_abs) 

```

Import the `FAS_pups.csv` file using a relative path.

```{r}
pubs_df = 
  read_csv("data/FAS_pups.csv")

pubs_df = 
  janitor::clean_names(pubs_df)
```

Import the same data set using an absolute path.

```{r}
pubs_df_abs= 
  read_csv("~/Desktop/data_wrangling_i/data/FAS_pups.csv")

pubs_df_abs = 
  janitor::clean_names(pubs_df_abs) 
```

##Look at data

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

You can use `View`

```{r, eval=FALSE} 
view(litters_df)
##use eval = FALSE so it wouldn't include in the r markdown
```

look at data summary: 2 ways 

```{r}
str(litters_df)
skimr::skim(litters_df) #with mean sd hist missing numbers
```

